# Generated by Django 4.2 on 2023-04-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="brand",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
