# Generated by Django 4.2 on 2023-04-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drf_stripe", "0004_alter_productfeature_id"),
        ("payment", "0002_payment_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="price_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="drf_stripe.price",
            ),
        ),
    ]
