# Generated by Django 4.2 on 2023-04-07 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_payment_price_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="price_id",
        ),
    ]
