# Generated by Django 4.2 on 2023-04-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recent",
            name="times",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
