# Generated by Django 4.2 on 2023-04-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom", "0002_alter_recent_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
