# Generated by Django 4.2 on 2023-04-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom", "0003_tip_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tip",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
